export default [
    {
        InternationalNo: '2',
        Country: '香港',
        InternationalCode: '852',
        regex: /^[456789]{1}(([\d]{7})|([\d]{8})|([\d]{12})){1}$/,
    },
    {
        InternationalNo: '3',
        Country: '澳門',
        InternationalCode: '853',
        regex: /^[6]{1}([\d]{7})$/,
    },
    {
        InternationalNo: '0',
        Country: '台灣',
        InternationalCode: '886',
        regex: /^9[\d]{8}$/,
    },
    {
        InternationalNo: '1',
        Country: '中國',
        InternationalCode: '86',
        regex: /^[1]{1}([\d]{10})$/,
    },
    // {
    //     InternationalNo: '4',
    //     Country: '新加坡',
    //     InternationalCode: '65',
    //     regex: /^[13689]{1}([\d]{6,8})$/,
    // },
    // {
    //     InternationalNo: '5',
    //     Country: '馬來西亞',
    //     InternationalCode: '60',
    //     regex: /^[1]{1}([\d]{8,9})$/,
    // },
    // {
    //     InternationalNo: '8',
    //     Country: '美國',
    //     InternationalCode: '1',
    //     regex: /^([\d]{10,12})$/,
    // },
    // {
    //     InternationalNo: '12',
    //     Country: '澳洲',
    //     InternationalCode: '61',
    //     regex: /^[4]{1}([\d]{8,9})$/,
    // },
    // {
    //     InternationalNo: '11',
    //     Country: '加拿大',
    //     InternationalCode: '1',
    //     regex: /^([\d]{10})$/,
    // },
    // {
    //     InternationalNo: '7',
    //     Country: '越南',
    //     InternationalCode: '84',
    //     regex: /^[1-9]{1}([\d]{6,9})$/,
    // },
    // {
    //     InternationalNo: '6',
    //     Country: '泰國',
    //     InternationalCode: '66',
    //     regex: /^[1-9]{1}([\d]{7,8})$/,
    // },
    // {
    //     InternationalNo: '9',
    //     Country: '菲律賓',
    //     InternationalCode: '63',
    //     regex: /^[24579]{1}(([\d]{7,9})|([\d]{12}))?$/,
    // },
    // {
    //     InternationalNo: '14',
    //     Country: '韓國',
    //     InternationalCode: '82',
    //     regex: /^[17]{1}([\d]{8,9})$/,
    // },
    // {
    //     InternationalNo: '16',
    //     Country: '紐西蘭',
    //     InternationalCode: '64',
    //     regex: /^[278]{1}([\d]{7,9})$/,
    // },
    // {
    //     InternationalNo: '15',
    //     Country: '日本',
    //     InternationalCode: '81',
    //     regex: /^[789]{1}([\d]{8,9})$/,
    // },
    // {
    //     InternationalNo: '13',
    //     Country: '印度',
    //     InternationalCode: '91',
    //     regex: /^([\d]{6,12})$/,
    // },
    // {
    //     InternationalNo: '17',
    //     Country: '英國',
    //     InternationalCode: '44',
    //     regex: /^[34789]{1}(([\d]{8,9})|([\d]{11,12}))?$/,
    // },
    // {
    //     InternationalNo: '20',
    //     Country: '印尼',
    //     InternationalCode: '62',
    //     regex: /^[29]{1}([\d]{7,11})$/,
    // },
    // {
    //   InternationalNo: '10',
    //   Country: '杜拜',
    //   InternationalCode: '971',
    // },
    // {
    //   InternationalNo: '21',
    //   Country: '柬埔寨',
    //   InternationalCode: '855',
    // },
    // {
    //   InternationalNo: '19',
    //   Country: '法國',
    //   InternationalCode: '33',
    // },
    // {
    //   InternationalNo: '18',
    //   Country: '德國',
    //   InternationalCode: '49',
    // },
    // {
    //   InternationalNo: '22',
    //   Country: '緬甸',
    //   InternationalCode: '95',
    // },
]
