export enum EHeaderTheme {
    dark = 'dark',
    light = 'light',
}

export enum EApiErrorKey {
    // AUTH_PROVIDER_NOT_EXIST = 'AUTH_PROVIDER_NOT_EXIST',
    // BOUND_USER = 'BOUND_USER',
    // INVALID_FORM_DATA = 'INVALID_FORM_DATA',
    // INVALID_AUTH_MODEL = 'INVALID_AUTH_MODEL',
    // INVALID_PASSWORD = 'INVALID_PASSWORD',
    // INVALID_TOKEN = 'INVALID_TOKEN',
    // TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    // TOO_MANY_OTP = 'TOO_MANY_OTP',
    // USER_BOUND = 'USER_BOUND',
    // USER_EXIST = 'USER_EXIST',
    // USER_NOT_FOUND = 'USER_NOT_FOUND',
    // INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
    // INVALID_EMAIL_OTP = 'INVALID_EMAIL_OTP',
    // INVALID_RESET_PASSWORD_CODE = 'INVALID_RESET_PASSWORD_CODE',
    // INVALID_VERIFICATION_CODE = 'INVALID_VERIFICATION_CODE',
    // NOT_VERIFIED_EMAIL = 'NOT_VERIFIED_EMAIL',
    // USER_REGISTERED_ALREADY = 'USER_REGISTERED_ALREADY',
    default = 'default',
}
